// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8umES1sa2RFlT1jF1krVVcBib11XebR4',
    appId: '1:988133577056:web:0fb7cd33e7653a2f320e05',
    messagingSenderId: '988133577056',
    projectId: 'fir-analystic-2fc4c',
    authDomain: 'fir-analystic-2fc4c.firebaseapp.com',
    storageBucket: 'fir-analystic-2fc4c.appspot.com',
    measurementId: 'G-5HWDTSHE7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCAlaEtTG0-rBp4NAbWhhupCs-dUPgj60',
    appId: '1:988133577056:android:43a40f30ec39f4e1320e05',
    messagingSenderId: '988133577056',
    projectId: 'fir-analystic-2fc4c',
    storageBucket: 'fir-analystic-2fc4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsPJ2IftZcPHu8qDAOa4yG4llrnODJi1I',
    appId: '1:988133577056:ios:9c6feb1de802a5f4320e05',
    messagingSenderId: '988133577056',
    projectId: 'fir-analystic-2fc4c',
    storageBucket: 'fir-analystic-2fc4c.appspot.com',
    iosBundleId: 'com.example.msdProjectFoodDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsPJ2IftZcPHu8qDAOa4yG4llrnODJi1I',
    appId: '1:988133577056:ios:52cdb725c53fe61e320e05',
    messagingSenderId: '988133577056',
    projectId: 'fir-analystic-2fc4c',
    storageBucket: 'fir-analystic-2fc4c.appspot.com',
    iosBundleId: 'com.example.msdProjectFoodDiary.RunnerTests',
  );
}
